version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ksai-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ksai-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
